### ISSUE TITLE
TODO Apps (for bettering the platform)

### ISSUE THREAD

**Issue by saurshaz** [saurshaz/riot-dyna#18]
#### TODO apps
- [x]  riotauth (social auth-client with riot and auth-service)
- [ ] - riotgrid (crud grid with riot and fyler)
- [ ] - riotgram (instagram API with riot, search and display images  and oneapi)
- [ ] - riotdit (reddit/hackernews/RSS browser with riot and oneapi)
- [ ] - riotwer (twitter client with riot and oneapi)
- [ ] - riotabnb (abnb clone with riot and oneapi)
